enum AppPage {
  home,
  preferences,
  generator,
  resources,
  mapMaker,
  playlists,
  users,
  classes,
  feats,
  items,
  languages,
  races,
  transformations,
  skills,
  spells,
  conditions,
  damageTypes,
  itemProperties,
  rules,
  spellTags,
  features,
  creatures,
  atlas,
  characters,
  organisations,
  events,
  lore,
  story,
}

String appPageTitle(AppPage page) => switch (page) {
      AppPage.home => 'RPG Manager',
      AppPage.preferences => 'Preferences',
      AppPage.generator => 'Generator',
      AppPage.resources => 'Resources',
      AppPage.mapMaker => 'Map maker',
      AppPage.playlists => 'Playlists',
      AppPage.users => 'Users',
      AppPage.classes => 'Classes',
      AppPage.feats => 'Feats',
      AppPage.items => 'Items',
      AppPage.languages => 'Languages',
      AppPage.races => 'Races',
      AppPage.transformations => 'Transformations',
      AppPage.skills => 'Skills',
      AppPage.spells => 'Spells',
      AppPage.conditions => 'Conditions',
      AppPage.damageTypes => 'Damage Types',
      AppPage.itemProperties => 'Item Properties',
      AppPage.rules => 'Rules',
      AppPage.spellTags => 'Spell Tags',
      AppPage.features => 'Features',
      AppPage.creatures => 'Creatures',
      AppPage.atlas => 'Atlas',
      AppPage.characters => 'Characters',
      AppPage.organisations => 'Organisations',
      AppPage.events => 'Events',
      AppPage.lore => 'Lore',
      AppPage.story => 'Story',
    };
